spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flowable?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    test-on-borrow: true
    validation-query: SELECT 1

    maximum-pool-size: 20
    hikari.max-lifetime: 30000
    hikari.idle-timeout: 30000
    data-source-properties:
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      cachePrepStmts: true
      useServerPrepStmts: true


flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  process-definition-location-prefix: "classpath*:/processes/"
  process-definition-location-suffixes: "**.bpmn20.xml,**.bpmn"
