package rules;

import org.fran.demo.drools.fact.*;
import java.util.ArrayList;

rule "contain_match_member_1"
    when
        $order:Order();
        $user:User(orderList contains $order)
    then
        System.out.println("包含FactOrder 且user包含OrderList");
end

rule "contain_match_member_2"
    when
        $order:Order();
        $user:User(orderList not contains $order)
    then
        System.out.println("包含FactOrder 且user不包含OrderList");
end

rule "contain_match_member_3"
    when
        User(name matches "张.*")
    then
        System.out.println("user name 包含【张】");
end

rule "contain_match_member_4"
    when
        $array:ArrayList();
        $u:User(name memberOf $array);
    then
        System.out.println("user name 包含在list中");
end

rule "contain_match_member_5"
    when
        $c:String();
        $u:User(name memberOf $c);
    then
        System.out.println("user name 包含张");
end