package rules;//package对应的不一定是真正的目录。可以任意写，同一个包下的drl文件可以相互访问

import org.fran.demo.drools.springboot.fact.Order;//引入类

rule "score_1"
when
    $order:Order(amount<100)
then
    $order.setScore(0);
    System.out.println("100元以下 不积分");
end

rule "score_2"
when
    $order:Order(amount >=100 && amount<500)
then
    $order.setScore(100);
    System.out.println("100元-500元 积100分");
end

rule "score_3"
when
    $order:Order(amount >=500 && amount<1000)
then
    $order.setScore(500);
    System.out.println("500元-1000元 积500分");
end

rule "score_4"
when
    $order:Order(amount >=1000)
then
    $order.setScore(1000);
    System.out.println("1000元以上 积1000分");
end

